### ISSUE TITLE
Win11_23H2 prompt does not support

### ISSUE THREAD

**Issue by YuI2333** [res2k/HDRTray#11]
Win11_23H2_22631.3737 prompt does not support, I wrote wrong? Please help me, thanks!

![24-06-19_23-40-33](https://github.com/res2k/HDRTray/assets/26202875/ef9ef108-62b7-429f-a110-209a8955b1a2)

**Comment by res2k** [comment]
Thanks for the report. I made a rather stupid mistake.

I've fixed the bug and made a new release: https://github.com/res2k/HDRTray/releases/tag/v0.5.2

Please give it a try, and close the issue if it now works for you.
