### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by Loban79** [res2k/HDRTray#12]
Would love to be able to donate to keep this project evolving.  I'd love to see more features added.  A donate link either in the README or in a context menu would be great!

**Comment by res2k** [comment]
Thank you for your kind words. However, won't be providing means to donation any time soon.

Why is that? I'm doing this project in my free time for a mix of "selfish" reasons: my own needs, for the joy of programming, maybe to try out some stuff I find interesting. If I'd add means of donating, and people donate, I feel this might create a sense of expectations and obligations - expectations by those who donate that the project would keep evolving, and on my side, a feeling of obligation to keep trying to do so.
However, I'd rather have the freedom to do what I want with it, when I want to - including not doing anything for a stretch of time.

That said, feel free to show your appreciation by letting me know that this little program is useful for you, by leaving feedback, and by reporting any problems you encounter on the way. I'll try to address any problems to the best of the abilities and consider all the feedback given - just on my own time :)
