### ISSUE TITLE
HDR Not supported even if my monitor supports it

### ISSUE THREAD

**Issue by echo-matt** [res2k/HDRTray#16]
The tray icon displays the error "HDR not supported" even if my monitor is HDR capable, the cmd utility works and i can turn on and off hdr with that, but i can't with the tray icon.
Monitor 2822NE has HDR on but i'm unable to toggle it via the tray icon.

![image](https://github.com/user-attachments/assets/a143e352-8cbe-4007-a2fe-3ebeec72b976)

**Comment by res2k** [comment]
Hi,
I messed something up when dealing with multiple displays.
It should be fixed in the latest release: https://github.com/res2k/HDRTray/releases/tag/v0.5.4, please give it a try.
