### ISSUE TITLE
Add keyboard shortcut to toggle

### ISSUE THREAD

**Issue by echo-matt** [res2k/HDRTray#17]
I don't know if it's possible but could you add a keyboard shortcut to toggle HDR on/off?

**Comment by res2k** [comment]
You can use Win+Alt+B for that.

**Comment by echo-matt** [comment]
> You can use Win+Alt+B for that.

Win+Alt+B is exclusive to Xbox Game Bar and i have that disabled because it's kinda trash

**Comment by indigofairyx** [comment]
if you use autohotkey this is easy to set up.


```
global hdrToggle := false
^#h::
    hdrToggle := !hdrToggle ; Toggle the state
    ; Check the state and run the corresponding command
    if (hdrToggle) {
        Run, "C:\Portable Programs\HDR Tray CMD\HDRCmd.exe" "on"
    } else {
        Run, "C:\Portable Programs\HDR Tray CMD\HDRCmd.exe" "off"
    }
Return
```

**Comment by res2k** [comment]
> if you use autohotkey this is easy to set up.

Thanks! I've added a pinned issue with your code so it's more visible.
