### ISSUE TITLE
no issue, just Thank You!!! 

### ISSUE THREAD

**Issue by indigofairyx** [res2k/HDRTray#18]
no issue, just Thank You!!!  this little utility is fantastic! 🤩

I've built it into my autohotkey gui has a toggle and hotkey...

![image](https://github.com/user-attachments/assets/37ddd724-2741-4b34-8389-7330a04ca667)
![image](https://github.com/user-attachments/assets/8d610ea9-75c0-4041-b79a-76940dfffb65)

**Comment by res2k** [comment]
Thank you for your comment, and sharing the AutoHotkey snippet!
