### ISSUE TITLE
Add key shortcut to toggle HDR

### ISSUE THREAD

**Issue by Kathaarian** [res2k/HDRTray#2]
Hi,

Been using the 0.2 version and it works perfectly,  so thank you! A key shortcut to toggle between SDR and HDR would be a very welcome addition, since I don't use the Xbox Game Bar app myself (installing such a bloated piece of software just for its toggle functionality seems like overkill).

Apologies btw. if this isn't the right place for feedback and suggestions and thanks again for making HDRTray!

**Comment by res2k** [comment]
Hi,
yes, this is the right place for feedback/suggestions:

As to your specific suggestions of adding a keyboard shortcut:
I unfortunately have little reason/motivation to do that - first, I consider it redundant with the shortcut provided by the mentioned Xbox Game Bar, and second, I hardly even use _that_ shortcut feature.

**Comment by indigofairyx** [comment]
if you use auto hotkey that's easy to set up...

```
global hdrToggle := false


^#h::    
    hdrToggle := !hdrToggle ; Toggle the state
    ; Check the state and run the corresponding command
    if (hdrToggle) {
        Run, "C:\Portable Programs\HDR Tray CMD\HDRCmd.exe" "on"
    } else {
        Run, "C:\Portable Programs\HDR Tray CMD\HDRCmd.exe" "off"
    }
Return
```
